version: 2
jobs:
  validate:
    docker:
      - image: broadinstitute/terraform:0.11.8
        entrypoint: /bin/bash
    steps:
      - checkout
      - run:
          name:
          command: |
            cd ./terraform/aws
            terraform init
            terraform validate
            terraform plan
  deploy:
    docker:
      - image: broadinstitute/terraform:0.11.8
        entrypoint: /bin/bash
    steps:
      - checkout
      - run:
          name:
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test-deploy:
    jobs:
      - validate
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: /^master$/
