kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/azure-disk
parameters:
  cachingmode: None
  kind: Managed
  storageaccounttype: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
